### PR TITLE
Detect getMockBuilder

### PR DESCRIPTION
**Pull request by ruudk**
It should also detect PHPUnit's `\PHPUnit\Framework\TestCase::getMockBuilder`.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
How does PHPUnit code with this method look like? Just to verify

**Comment by ruudk** [comment]
```php
$mock = $this->getMockBuilder(FetchMethod::class)
            ->disableOriginalConstructor()
            ->onlyMethods($methods)
            ->getMock();
```

So that works the same as:
```php
$mock =  $this->createMock(EventRecorder::class);
```

I did not test it, but I feel this is the same thing.

**Comment by ruudk** [comment]
I think we should also do the same for `createStub`.

**Comment by TomasVotruba** [comment]
Could you test it locally, please? Otherwise we'll have to add testing suite to make sure these are picked up correctly. Which we might have as well :)

**Comment by ruudk** [comment]
Ok, I just tested it and it does work perfectly!

**Pull request merged**
